# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Activities
    url: activities/
    weight: 20
  - name: Topics
    url: tags/
    weight: 20
  - name: Contact
    url: contact/
    weight: 30
