# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blog
    url: blog/
    weight: 11
  - name: Latest Activities
    url: /activities
    weight: 12
  - name: Topics
    url: tags/
    weight: 40
  - name: CV
    url: cv/
    weight: 60
