# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blog
    url: blog/
    weight: 20
  - name: News
    url: news/
    weight: 30
  - name: Topics
    url: tags/
    weight: 40
  - name: CV
    url: cv/
    weight: 60
